name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: ls
      run: ls -la /home/runner/work/emoji-utils-java/emoji-utils-java/gradle/wrapper/gradle-wrapper.jar
    - name: Build with Gradle
      run: bash -x ./gradle build
